/* Catolicismo: obras em tradução (índice). Gerado por ferramentas/traducoes.py;
   o texto de cada obra fica em conteudo/<autor>/<obra>.js e só é carregado quando a obra é aberta.
   (Santa Teresinha tem índice próprio: conteudo/santa-teresinha/indice.js.) */

BIBLIOTECA.obra({"id": "vida-de-santo-antao", "autor": "santo-atanasio", "titulo": "Vida de Santo Antão", "ano": 357, "datas": "c. 357", "genero": "Hagiografia", "divisao": {"singular": "parte", "plural": "partes", "rotulo": "nome"}, "traducao": {"lingua": "grego", "codigo": "grc", "titulo": "Βίος Ἀντωνίου"}, "arquivo": "conteudo/santo-atanasio/vida-de-santo-antao.js", "_palavras": 21171, "partes": [{"n": "Prólogo, 1–15", "titulo": "A vocação e os primeiros combates"}, {"n": "16–43", "titulo": "O discurso aos monges"}, {"n": "44–66", "titulo": "A montanha interior"}, {"n": "67–88", "titulo": "A fé e a sabedoria de Antão"}, {"n": "89–94", "titulo": "A morte de Antão"}]});
BIBLIOTECA.obra({"id": "confissoes", "autor": "santo-agostinho", "titulo": "Confissões", "ano": 397, "datas": "c. 397–401", "genero": "Autobiografia", "divisao": {"singular": "livro", "plural": "livros"}, "traducao": {"lingua": "latim", "codigo": "la", "titulo": "Confessiones"}, "arquivo": "conteudo/santo-agostinho/confissoes.js", "_palavras": 105975, "partes": [{"n": "Livro I", "titulo": ""}, {"n": "Livro II", "titulo": ""}, {"n": "Livro III", "titulo": ""}, {"n": "Livro IV", "titulo": ""}, {"n": "Livro V", "titulo": ""}, {"n": "Livro VI", "titulo": ""}, {"n": "Livro VII", "titulo": ""}, {"n": "Livro VIII", "titulo": ""}, {"n": "Livro IX", "titulo": ""}, {"n": "Livro X", "titulo": ""}, {"n": "Livro XI", "titulo": ""}, {"n": "Livro XII", "titulo": ""}, {"n": "Livro XIII", "titulo": ""}]});
BIBLIOTECA.obra({"id": "introducao-a-vida-devota", "autor": "sao-francisco-de-sales", "titulo": "Introdução à vida devota (Filoteia)", "ano": 1609, "datas": "1609; texto definitivo de 1619", "genero": "Espiritualidade", "divisao": {"singular": "parte", "plural": "partes"}, "traducao": {"lingua": "francês", "codigo": "fr", "titulo": "Introduction à la vie dévote"}, "arquivo": "conteudo/sao-francisco-de-sales/introducao-a-vida-devota.js", "_palavras": 88409, "partes": [{"n": "", "titulo": "Oração dedicatória e Prefácio"}, {"n": "I", "titulo": "Primeira parte: do primeiro desejo à resolução de abraçar a vida devota"}, {"n": "II", "titulo": "Segunda parte: a oração e os sacramentos"}, {"n": "III", "titulo": "Terceira parte: o exercício das virtudes"}, {"n": "IV", "titulo": "Quarta parte: contra as tentações mais comuns"}, {"n": "V", "titulo": "Quinta parte: renovar a alma e confirmá-la na devoção"}]});
BIBLIOTECA.obra({"id": "ortodoxia", "autor": "g-k-chesterton", "titulo": "Ortodoxia", "ano": 1908, "genero": "Ensaio", "divisao": {"singular": "capítulo", "plural": "capítulos"}, "traducao": {"lingua": "inglês", "codigo": "en", "titulo": "Orthodoxy"}, "arquivo": "conteudo/g-k-chesterton/ortodoxia.js", "_palavras": 62399, "partes": [{"n": "", "titulo": "Prefácio"}, {"n": "I", "titulo": "Introdução em defesa de todo o resto"}, {"n": "II", "titulo": "O maníaco"}, {"n": "III", "titulo": "O suicídio do pensamento"}, {"n": "IV", "titulo": "A ética da Terra dos Elfos"}, {"n": "V", "titulo": "A bandeira do mundo"}, {"n": "VI", "titulo": "Os paradoxos do cristianismo"}, {"n": "VII", "titulo": "A revolução eterna"}, {"n": "VIII", "titulo": "O romance da ortodoxia"}, {"n": "IX", "titulo": "A autoridade e o aventureiro"}]});
BIBLIOTECA.obra({"id": "alma-de-todo-apostolado", "autor": "dom-chautard", "titulo": "A alma de todo apostolado", "ano": 1912, "datas": "forma definitiva de 1912; texto da 12.ª edição, 1927", "genero": "Espiritualidade", "divisao": {"singular": "parte", "plural": "partes"}, "traducao": {"lingua": "francês", "codigo": "fr", "titulo": "L'Âme de tout apostolat"}, "arquivo": "conteudo/dom-chautard/alma-de-todo-apostolado.js", "_palavras": 77785, "partes": [{"n": "", "titulo": "Prelúdio"}, {"n": "I", "titulo": "Primeira parte: Deus quer as obras e a vida interior"}, {"n": "II", "titulo": "Segunda parte: união da vida ativa e da vida interior"}, {"n": "III", "titulo": "Terceira parte: a vida ativa, perigosa sem a vida interior, garante com ela o progresso na virtude"}, {"n": "IV", "titulo": "Quarta parte: fecundidade das obras pela vida interior"}, {"n": "V", "titulo": "Quinta parte: alguns princípios e conselhos para a vida interior"}, {"n": "", "titulo": "Epílogo"}]});
